# Generated by Django 6.0.4 on 2026-05-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_brand_category_new_delete_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='author',
            new_name='turi',
        ),
        migrations.AddField(
            model_name='new',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
